version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app_nest
  #   restart: always
  #   ports:
  #     - "3005:3005"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - mysql
  #   env_file: .env

volumes:
  mysql_data: